@url = http://localhost:8000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMDEsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc0OTU2MzcwMiwiZXhwIjoxNzQ5NTY0NjAyfQ.sRtrXBM3lZd0Hyh1mhynCXYn4vc7DwQs2mk_-rTNV0A
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMDIsImVtYWlsIjoidXNlcjEwMDFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDk0NTkxMjQsImV4cCI6MTc1MDA2MzkyNH0.G82dgORK7HQGI4sL8zt7_5DTRuS_vX7YXBT8-8RZvv8


### Seed the database with initial data
###
POST {{url}}/seed

### Get all users
### 
GET {{url}}/users
Authorization:  Bearer {{access_token}}

### users
### create a new user
###
POST {{url}}/users
Content-Type: application/json

{
  "email": "mukirisimon22@gmail.com",
  "password": "securePass123",
  "firstName": "simon",
  "lastName": "njoroge",
  "role": "user",
  "phoneNumber": "+254717322552",
  "profilePicture": "https://example.com/images/profile.jpg"
}

### Get a user by ID
###
GET {{url}}/users/1
Authorization:  Bearer {{access_token}}

### Update a user by ID
###
PUT {{url}}/users/1
Content-Type:  application/json

{
  "email": "user@example.com",
  "password": "securePass123",
  "firstName": "John",
  "lastName": "Doe",
  "role": "user",
  "phoneNumber": "+1234567890",
  "profilePicture": "https://example.com/images/profile.jpg"
}


### Delete a user by ID
###
DELETE {{url}}/users/1001

### login

### User LOGIN
###
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securePass123"
}

### logout
###
POST {{url}}/auth/logout/1
Authorization:  Bearer {{access_token}}


### refresh-token
###
POST {{url}}/auth/refresh-token


### forgot-password
###
POST {{url}}/auth/forgot-password
Content-Type: application/json

{
  "email": "mukirisimon22@gmail.com"
}

### Reset Password
###
POST {{url}}/auth/reset-password
Content-Type: application/json

{
  "token":"",
  "newPassword": "newSecurePass123"
}


### tour-package
### Create a new tour package
###
POST {{url}}/tour-packages
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "title": "Amazing Tour",
  "description": "Explore the wonders of the world with our amazing tour package.",
  "price": 299.99,
  "startDate": "2023-10-01",
  "endDate": "2023-10-06",
  "location": "Paris, France",
  "coverImage": "https://example.com/images/tour.jpg",
  "itinerary": "hi"
}

### Get all tour packages
###
GET {{url}}/tour-packages
Authorization:  Bearer {{access_token}}

### Get a tour package by ID
###
GET {{url}}/tour-packages/1
Authorization:  Bearer {{access_token}}
### Update a tour package by ID
###
PUT {{url}}/tour-packages/1
Content-Type: application/json

{
  "title": "Amazing Tour Updated",
  "description": "Explore the wonders of the world with our amazing tour package, now updated.",
  "price": 249.99,
  "duration": "6 days",
  "imageUrl": "https://example.com/images/tour-updated.jpg",
  "availableSeats": 15
}
### Delete a tour package by ID
###
DELETE {{url}}/tour-packages/1
Authorization:  Bearer {{access_token}}
### Booking
### Create a new booking
###
POST {{url}}/bookings
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "userId": 1,
  "tourPackageId": 1,
  "bookingDate": "2023-10-01",
  "numberOfSeats": 2
}

### Get all bookings
###
GET {{url}}/bookings
Authorization:  Bearer {{access_token}}
### Get a booking by ID
###
GET {{url}}/bookings/1
Authorization:  Bearer {{access_token}}
### Update a booking by ID
###
PUT {{url}}/bookings/1
Content-Type: application/json

{
  "userId": 1,
  "tourPackageId": 1,
  "bookingDate": "2023-10-02",
  "numberOfSeats": 3
}

### Delete a booking by ID
###
DELETE {{url}}/bookings/1

### tickets
### Create a new ticket
###
POST {{url}}/tickets
Content-Type: application/json

{
  "userId": 1,
  "tourPackageId": 1,
  "bookingId": 1,
  "ticketDate": "2023-10-01",
  "seatNumber": "A1"
}
### Get all tickets
###
GET {{url}}/tickets
Authorization:  Bearer {{access_token}}

### Get a ticket by ID
###
GET {{url}}/tickets/1
Authorization:  Bearer {{access_token}}
### Update a ticket by ID
###
PUT {{url}}/tickets/1
Content-Type: application/json

{
  "userId": 1,
  "tourPackageId": 1,
  "bookingId": 1,
  "ticketDate": "2023-10-02",
  "seatNumber": "A2"
}

### Delete a ticket by ID
###
DELETE {{url}}/tickets/1

### inquiries
### Create a new inquiry
###
POST {{url}}/inquiries
Content-Type: application/json

{
  "userId": 1,
  "subject": "Inquiry about tour packages",
  "message": "I would like to know more about the available tour packages."
}

### Get all inquiries
###
GET {{url}}/inquiries
Authorization:  Bearer {{access_token}}
### Get an inquiry by ID
###
GET {{url}}/inquiries/1
Authorization:  Bearer {{access_token}}
### Update an inquiry by ID
###
PUT {{url}}/inquiries/1
Content-Type: application/json

{
  "userId": 1,
  "subject": "Updated Inquiry about tour packages",
  "message": "I would like"
}





