@url = http://localhost:8000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoibXVraXJpLjE2MDMwQHN0dWRlbnRzLmt5dS5hYy5rZSIsImNsYWltcyI6WyJ1c2VyIiwiZ2V0OnVzZXIiLCJjcmVhdGU6dXNlciIsInVwZGF0ZTp1c2VyIiwiZGVsZXRlOnVzZXIiLCJhZGQ6dG91cnBhY2thZ2UiLCJnZXQ6dG91cnBhY2thZ2UiXSwiaWF0IjoxNzQ5ODIzNTUwLCJleHAiOjE3NDk4MjQ0NTB9.t_RWTnCaM3zFDyZUSmZ6Ouin8MfEHu5GTkF8zFpwOsQ
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibXVraXJpc2ltb24yMkBnbWFpbC5jb20iLCJjbGFpbXMiOlsidXNlciIsImdldDp1c2VyIiwiY3JlYXRlOnVzZXIiLCJ1cGRhdGU6dXNlciIsImRlbGV0ZTp1c2VyIiwiYWRkOnRvdXJwYWNrYWdlIiwiZ2V0OnRvdXJwYWNrYWdlIl0sImlhdCI6MTc0OTgxMDM1MywiZXhwIjoxNzUwNDE1MTUzfQ.M4BRXWroJVde6p-lBMXAsCPfO08byuwjWqNnH2O2mKE

### Seed the database with initial data
###
POST {{url}}/seed

### users Routes ###
### Get all users
### 
GET {{url}}/users
Authorization:  Bearer {{access_token}}

### Get user by id
GET {{url}}/users/1000000
Authorization:  Bearer {{access_token}}


### users
### create a new user
###
POST {{url}}/users
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "email": "mukiri.16030@students.kyu.ac.ke",
  "fullName": "Simon Njoroge Mukiri",
  "role": "admin",
  "phone": "+254717322552",
  "profilePicture": "https://example.com/images/profile.jpg",
  "claims": [
    "user",
    "get:user",
    "create:user",
    "update:user",
    "delete:user",
    "add:tourpackage",
    "get:tourpackage"]
}


### Get a user by ID
###
GET {{url}}/users/10002
Authorization:  Bearer {{access_token}}

### Update a user by ID
###
PUT {{url}}/users/1002
Authorization:  Bearer {{access_token}}
Content-Type:  application/json

{
  "email": "mukirisimon22@gmail.com",
  "firstName": "simon",
  "lastName": "Njoroge",
  "role": "user",
  "phoneNumber": "+254717322552",
  "profilePicture": "https://example.com/images/profile.jpg"
}



### Delete a user by ID
###
DELETE {{url}}/users/4
Authorization:  Bearer {{access_token}}

### login

### User LOGIN
###
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "mukiri.16030@students.kyu.ac.ke",
  "password": "U9{n7*<[2PC{"
}

### logout
###
POST {{url}}/auth/logout/5
Authorization:  Bearer {{access_token}}


### refresh-token
###
POST {{url}}/auth/refresh-token


### forgot-password
###
POST {{url}}/auth/forgot-password
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "email": "mukirisimon22@gmail.com"
}

### Reset Password
###
POST {{url}}/auth/reset-password
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMDIsImVtYWlsIjoibXVraXJpc2ltb24yMkBnbWFpbC5jb20iLCJpYXQiOjE3NDk2MjI1NjcsImV4cCI6MTc0OTYyMzQ2N30.Mh83elFY_PAb20iaCK1h0ARSa8hwGKcb7nyjPKBUfcU",
  "newPassword": "newSecurePass12"
}


### tour-package routes ###
### get all 
GET {{url}}/tour-packages?page=1
Authorization:  Bearer {{access_token}}

### get by Id
GET {{url}}/tour-packages/251
Authorization:  Bearer {{access_token}}

### post
POST {{url}}/tour-packages
Authorization:  Bearer {{access_token}}
Content-Type: application/json

 {
    "title": "Mount Kenya Hiking Tour",
    "description": "Trek Africa’s second highest peak over a 5-day mountain adventure.",
    "location": "Mount Kenya, Kenya",
    "price": 950,
    "durationDays": 5,
    "imageUrl": "https://example.com/images/mt-kenya.jpg"
  }


### update tour package
PUT {{url}}/tour-packages/1
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "title":"",
  "description":"",
  "location":"",
  "price":"",
  "durationDays":"",
  "imageUrl":""
}

### delete tour package
DELETE {{url}}/tour-packages/1
Authorization:  Bearer {{access_token}}


### ticket routes ###
### get all tickets
GET {{url}}/tickets
Authorization:  Bearer {{access_token}}

### get by id
GET {{url}}/tickets/1
Authorization:  Bearer {{access_token}}

### post tickets
POST {{url}}/tickets
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "tourPackageId":"",
  "bookingId":"",
  "travelerName":"",
  "travelerEmail":"",
  "travelerPhone":""
}

### update tickets
PUT {{url}}/tickets/1
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "tourPackageId":"",
  "bookingId":"",
  "travelerName":"",
  "travelerEmail":"",
  "travelerPhone":""
}

### Delete Packets
DELETE {{url}}/tickets/1
Authorization:  Bearer {{access_token}}

### review routes ###
### get all riviews
GET {{url}}/reviews
Authorization:  Bearer {{access_token}}

### get review by id
GET {{url}}/reviews/1
Authorization:  Bearer {{access_token}}

### post review
POST {{url}}/reviews
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "userId":"",
  "tourPackageId":"",
  "rating":"",
  "comment":""
}

### update review
PUT {{url}}/reviews/1
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "userId":"",
  "tourPackageId":"",
  "rating":"",
  "comment":""
}

### delete review
DELETE {{url}}/reviews/1
Authorization:  Bearer {{access_token}}


### payment routes ###
### get all payments
GET {{url}}/payments
Authorization:  Bearer {{access_token}}

### get payment by id
GET {{url}}/payments/1
Authorization:  Bearer {{access_token}}

### stk push
POST {{url}}/payments/stk-push
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "bookingId":2,
  "amount":850,
  "phone":"0717322552",
  "method":"mpesa",
}

### post payment
POST {{url}}/payments
Authorization:  Bearer {{access_token}}
Content-Type: application/json


### UPDATE PAYMENT
PUT {{url}}/payments/1
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "bookingId":"",
  "transactionId":"",
  "amount":"",
  "paidAt":"",
  "method":"",
  "status":""
}

### delete payment 
DELETE {{url}}/payments
Authorization:  Bearer {{access_token}}


### inquiries routes ###
### get all inquiries
GET {{url}}/inquiries
Authorization:  Bearer {{access_token}}

### get by id
GET {{url}}/inquiries/1
Authorization:  Bearer {{access_token}}

### post inquiry
POST {{url}}/inquiries
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "tourPackageId":"",
  "userId":"",
  "message":"",
  "submittedAt":""
}

### update inquiries
PUT {{url}}/inquiries/1
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "tourPackageId":"",
  "userId":"",
  "message":"",
  "submittedAt":""
}

### delete inquiry
DELETE {{url}}/inquiries/1
Authorization:  Bearer {{access_token}}



### booking routes ###
### get all booking
GET {{url}}/bookings
Authorization:  Bearer {{access_token}}

### get booking by id
GET {{url}}/bookings/1
Authorization:  Bearer {{access_token}}

### post booking 
POST {{url}}/bookings
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "userId":1005,
  "tourPackageId":4,
  "bookingDate":"2025-06-11T12:00:00Z",
  "numberOfPeople":6,
  "status":"pending",
  "notes":"N/A"
}

### update booking
PUT {{url}}/bookings/1
Authorization:  Bearer {{access_token}}
Content-Type: application/json

{
  "userId":1005,
  "tourPackageId":4,
  "bookingDate":"2025-06-11T12:00:00Z",
  "numberOfPeople":6,
  "status":"pending",
  "notes":"N/A"
}

### delete booking
DELETE {{url}}/bookings/1
Authorization:  Bearer {{access_token}}








